services:
  db:
    image: postgres:13
    container_name: autofin_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: autofin_db
      POSTGRES_USER: autofin_user
      POSTGRES_PASSWORD: autofin_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
